services:
  frontend:
    build:
      context: ../.. 
      dockerfile: conf/app/frontend/Dockerfile
    container_name: angular-frontend
    ports:
      - "4200:80"
    networks:
      - app-network

  backend:
    build:
      context: ../.. 
      dockerfile: conf/app/backend/Dockerfile
    container_name: spring-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/amermanager?currentSchema=amermanager
      SPRING_DATASOURCE_USERNAME: robob
      SPRING_DATASOURCE_PASSWORD: Qwerty.1
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    external: true
